services:
  server:
    image: h2os-image
    container_name: h2os-container
    hostname: h2os

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      - TZ=<your-timezone>  # e.g America/New_York

    ports:
      - "8080:8080"
      - "8282:8282"

    volumes:
      - h2os-volume:/app

volumes:
  h2os-volume:
